{
 "title": "Market Pulse - Sprint 1",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Stock Prices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n       timestamp as time,\n       close as value,\n       symbol as metric\n   FROM stock_prices \n   WHERE symbol IN ('AAPL', 'GOOGL', 'MSFT')\n       AND $__timeFilter(timestamp)\n   ORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Anamolies overtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n       timestamp as time,\n       COUNT(*) as anomalies\n   FROM anomalies \n   WHERE $__timeFilter(timestamp)\n   GROUP BY timestamp\n   ORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Anamolies by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n       method,\n       COUNT(*) as total_anomalies,\n       ROUND(AVG(score)::numeric, 2) as avg_score,\n       MIN(timestamp)::date as first_detection,\n       MAX(timestamp)::date as last_detection\n   FROM anomalies \n   GROUP BY method \n   ORDER BY total_anomalies DESC;"
    },
    {},
    {},
    {}
   ]
  }
 ]
}